import { err, ok } from './result';
import type { Result } from './result';

/**
 * The id that ties together everything one piece of work writes: log lines, audit rows and
 * events. It is always generated by the platform, never chosen by a caller (ADR-0020
 * decision 8).
 */
export type CorrelationId = string & { readonly __brand: 'CorrelationId' };

// The single definition of the rule. The database repeats it as a CHECK constraint.
const CORRELATION_ID = /^[A-Za-z0-9._-]{8,128}$/;

export function parseCorrelationId(
  text: string,
): Result<CorrelationId, { readonly code: 'correlation-id.invalid' }> {
  // The run-time type check matters: RegExp.test() would turn an array into a string.
  if (typeof text !== 'string' || !CORRELATION_ID.test(text)) {
    return err({ code: 'correlation-id.invalid' });
  }
  return ok(text as CorrelationId);
}
